spring.application.name=security
#MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/security
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#Security Properties
security.jwt.secret-key=iamlearningjwtsecurityfromtechamplifiersforclearinnginterviews
security.jwt.expiration-time=360000
