spring.application.name=microservice2
server.port=8082

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost
# Percentage of failed calls to open the circuit (e.g., 50%)
resilience4j.circuitbreaker.instances.microservice1.failureRateThreshold=50
# Time in milliseconds the circuit stays open (e.g., 5 seconds)
resilience4j.circuitbreaker.instances.microservice1.waitDurationInOpenState=5000


# Minimum calls before the failure rate is calculated
resilience4j.circuitbreaker.instances.microservice1.minimumNumberOfCalls=10
# Automatically move to half-open state after wait duration
resilience4j.circuitbreaker.instances.microservice1.automaticTransitionFromOpenToHalfOpenEnabled=true


# Number of test calls allowed in half-open state
resilience4j.circuitbreaker.instances.microservice1.permittedNumberOfCallsInHalfOpenState=8

# Sliding window type: COUNT_BASED or TIME_BASED
resilience4j.circuitbreaker.instances.microservice1.slidingWindowType=COUNT_BASED
# Number of calls or time in seconds based on the type
resilience4j.circuitbreaker.instances.microservice1.slidingWindowSize=10

resilience4j.circuitbreaker.instances.microservice1.recordExceptions=java.lang.Exception
logging.level.io.github.resilience4j=DEBUG